<a href="https://colab.research.google.com/github/Cromana22/Google-Colab-Examples/blob/main/NumpyPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [ ]:
import numpy as np

In [13]:
One  = np.array(range(1,10))
print(One)
print(One[1])

[1 2 3 4 5 6 7 8 9]
2


In [27]:
Two = np.array([ [1, 2, 3] , [4, 5, 6] , [7, 8, 9] ])
print(Two)

print()
Two = np.arange(1,10).reshape(3,3)
print(Two)

print()
print(Two[1, :]) # row, column and : is a placeholder for "all"

print()
print(Two[:, 1]) # row, column and : is a placeholder for "all"

print()
print(Two[1, 1]) # row, column

print()
print(Two[0:2, :]) # row start index 0 up to (not including) index 2

print()
print(Two[:, 0:2]) # column start index 0 up to (not including) index 2

print()
print(Two[0:2:, 0:2]) # row and column start index 0 up to (not including) index 2

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[4 5 6]

[2 5 8]

5

[[1 2 3]
 [4 5 6]]

[[1 2]
 [4 5]
 [7 8]]

[[1 2]
 [4 5]]


Pandas

In [12]:
import pandas as pd

data = { "Name": ["Alice", "Bob", "Charlie"], "Age": [25, 30, 35], "Score": [85.5, 90.0, 88.0] }
df = pd.DataFrame(data)
print(df)

print()
print(df["Name"]) # select column
print()
print(df[["Name", "Score"]]) # select multiple columns
print()
print(df.iloc[0]) # first row (by position)
print()
print(df.loc[1, "Age"]) # row by position, column by label
print()
print(df[df["Score"] > 87]) # filter rows
print()
df.describe()

df["AgeGroup"] = pd.cut(df["Age"], bins=[0,35,60], labels=["Young","Senior"])

print()
print(df)
print(df.groupby("AgeGroup", observed=False).size())       # count per group, observed false will show empty groups
print(df.groupby("AgeGroup", observed=False)["Score"].mean())   # average score per age


      Name  Age  Score
0    Alice   25   85.5
1      Bob   30   90.0
2  Charlie   35   88.0

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

      Name  Score
0    Alice   85.5
1      Bob   90.0
2  Charlie   88.0

Name     Alice
Age         25
Score     85.5
Name: 0, dtype: object

30

      Name  Age  Score
1      Bob   30   90.0
2  Charlie   35   88.0


      Name  Age  Score AgeGroup
0    Alice   25   85.5    Young
1      Bob   30   90.0    Young
2  Charlie   35   88.0    Young
AgeGroup
Young    3
dtype: int64
AgeGroup
Young    87.833333
Name: Score, dtype: float64
